/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesMaAdvisoryRouteImport } from './routes/services.ma-advisory'
import { Route as ServicesBpoTransformationRouteImport } from './routes/services.bpo-transformation'
import { Route as ServicesAiDigitalTransformationRouteImport } from './routes/services.ai-digital-transformation'
import { Route as IndustriesPrivateEquityRouteImport } from './routes/industries.private-equity'
import { Route as IndustriesHealthcareRouteImport } from './routes/industries.healthcare'
import { Route as IndustriesFinancialServicesRouteImport } from './routes/industries.financial-services'

const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMaAdvisoryRoute = ServicesMaAdvisoryRouteImport.update({
  id: '/services/ma-advisory',
  path: '/services/ma-advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBpoTransformationRoute =
  ServicesBpoTransformationRouteImport.update({
    id: '/services/bpo-transformation',
    path: '/services/bpo-transformation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAiDigitalTransformationRoute =
  ServicesAiDigitalTransformationRouteImport.update({
    id: '/services/ai-digital-transformation',
    path: '/services/ai-digital-transformation',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesPrivateEquityRoute = IndustriesPrivateEquityRouteImport.update({
  id: '/industries/private-equity',
  path: '/industries/private-equity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesHealthcareRoute = IndustriesHealthcareRouteImport.update({
  id: '/industries/healthcare',
  path: '/industries/healthcare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesFinancialServicesRoute =
  IndustriesFinancialServicesRouteImport.update({
    id: '/industries/financial-services',
    path: '/industries/financial-services',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/industries/financial-services': typeof IndustriesFinancialServicesRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/private-equity': typeof IndustriesPrivateEquityRoute
  '/services/ai-digital-transformation': typeof ServicesAiDigitalTransformationRoute
  '/services/bpo-transformation': typeof ServicesBpoTransformationRoute
  '/services/ma-advisory': typeof ServicesMaAdvisoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/industries/financial-services': typeof IndustriesFinancialServicesRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/private-equity': typeof IndustriesPrivateEquityRoute
  '/services/ai-digital-transformation': typeof ServicesAiDigitalTransformationRoute
  '/services/bpo-transformation': typeof ServicesBpoTransformationRoute
  '/services/ma-advisory': typeof ServicesMaAdvisoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/industries/financial-services': typeof IndustriesFinancialServicesRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/private-equity': typeof IndustriesPrivateEquityRoute
  '/services/ai-digital-transformation': typeof ServicesAiDigitalTransformationRoute
  '/services/bpo-transformation': typeof ServicesBpoTransformationRoute
  '/services/ma-advisory': typeof ServicesMaAdvisoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/industries/financial-services'
    | '/industries/healthcare'
    | '/industries/private-equity'
    | '/services/ai-digital-transformation'
    | '/services/bpo-transformation'
    | '/services/ma-advisory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/industries/financial-services'
    | '/industries/healthcare'
    | '/industries/private-equity'
    | '/services/ai-digital-transformation'
    | '/services/bpo-transformation'
    | '/services/ma-advisory'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/industries/financial-services'
    | '/industries/healthcare'
    | '/industries/private-equity'
    | '/services/ai-digital-transformation'
    | '/services/bpo-transformation'
    | '/services/ma-advisory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  InsightsRoute: typeof InsightsRoute
  IndustriesFinancialServicesRoute: typeof IndustriesFinancialServicesRoute
  IndustriesHealthcareRoute: typeof IndustriesHealthcareRoute
  IndustriesPrivateEquityRoute: typeof IndustriesPrivateEquityRoute
  ServicesAiDigitalTransformationRoute: typeof ServicesAiDigitalTransformationRoute
  ServicesBpoTransformationRoute: typeof ServicesBpoTransformationRoute
  ServicesMaAdvisoryRoute: typeof ServicesMaAdvisoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ma-advisory': {
      id: '/services/ma-advisory'
      path: '/services/ma-advisory'
      fullPath: '/services/ma-advisory'
      preLoaderRoute: typeof ServicesMaAdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/bpo-transformation': {
      id: '/services/bpo-transformation'
      path: '/services/bpo-transformation'
      fullPath: '/services/bpo-transformation'
      preLoaderRoute: typeof ServicesBpoTransformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-digital-transformation': {
      id: '/services/ai-digital-transformation'
      path: '/services/ai-digital-transformation'
      fullPath: '/services/ai-digital-transformation'
      preLoaderRoute: typeof ServicesAiDigitalTransformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/private-equity': {
      id: '/industries/private-equity'
      path: '/industries/private-equity'
      fullPath: '/industries/private-equity'
      preLoaderRoute: typeof IndustriesPrivateEquityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/healthcare': {
      id: '/industries/healthcare'
      path: '/industries/healthcare'
      fullPath: '/industries/healthcare'
      preLoaderRoute: typeof IndustriesHealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/financial-services': {
      id: '/industries/financial-services'
      path: '/industries/financial-services'
      fullPath: '/industries/financial-services'
      preLoaderRoute: typeof IndustriesFinancialServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  InsightsRoute: InsightsRoute,
  IndustriesFinancialServicesRoute: IndustriesFinancialServicesRoute,
  IndustriesHealthcareRoute: IndustriesHealthcareRoute,
  IndustriesPrivateEquityRoute: IndustriesPrivateEquityRoute,
  ServicesAiDigitalTransformationRoute: ServicesAiDigitalTransformationRoute,
  ServicesBpoTransformationRoute: ServicesBpoTransformationRoute,
  ServicesMaAdvisoryRoute: ServicesMaAdvisoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
